services:
  devx:
    image: ghcr.io/rmkraus/workshop-framework/devx:main
    build:
      context: .
      dockerfile: Dockerfile
    # volumes:
    #   - .:/project:cached
    ports:
      - 8888:8888

